trading_params:
  instrument: 'EURUSDx'
  timeframe: 'M1'
  lot_size: 0.01
  contract_size: 100000
  starting_balance: 10000
  lookback_bars: 100000
  rsi_period: 14
  rsi_oversold: 30
  rsi_overbought: 70
  rsi_exit_level: 50
