trading_params:
  instrument: 'XAUUSDx'
  timeframe: 'M1'
  lot_size: 0.50
  contract_size: 100000
  starting_balance: 10000

  # Date range for historical data
  start_date: '2025-01-02'
  end_date: '2025-07-29'

  # Cache settings
  use_cache: true
  cache_dir: 'data/cache'
  rsi_period: 14
  rsi_oversold: 35
  rsi_overbought: 65
  rsi_exit_level: 50

  # RSI Momentum Filtering
  rsi_momentum_threshold: 2.0 # Minimum RSI points change required for entry signal
  use_momentum_filter: true # Enable/disable momentum confirmation

  # Trend Filter (prevents counter-trend trades)
  trend_filter:
    enabled: true # Enable/disable trend filtering
    fast_ema: 9 # Fast EMA period
    medium_ema: 21 # Medium EMA period  
    slow_ema: 50 # Slow EMA period
    strength_threshold: 0.002 # Minimum strength for strong trend (0.2%)

  # ATR Stop Loss parameters (Legacy - for reference)
  use_atr_stop: false # Disabled in favor of trailing stops
  atr_period: 14
  atr_multiplier: 1

  # ATR Trailing Stop System
  trailing_stops:
    enabled: true
    strategy: 'B' # Options: A (Pure), B (Time-based), C (Aggressive)
    allow_runtime_changes: true
    config_check_interval: 6000 # Check for config changes every N seconds


    # Strategy Descriptions:
    # A: Breakeven@1.5 ATR, Trail@1.0 ATR, Hard Stop@2.0 ATR (Conservative)
    # B: Breakeven@2.0 ATR, Trail@1.5 ATR, Hard Stop@2.5 ATR (Balanced)
    # C: Breakeven@1.0 ATR, Trail@0.75 ATR, Hard Stop@1.5 ATR (Aggressive)
